### ISSUE TITLE
装上MOD没有反应

### ISSUE THREAD

**Issue by G2012dis** [hetima/DSP_LongSorter#1]

**Comment by hetima** [comment]
Hold down ctrl key while construction.

https://user-images.githubusercontent.com/33700/123503242-acee5c80-d68c-11eb-9b67-c4af8da65953.mp4

**Comment by newbienoobplayer** [comment]
cool, but what does it mean well it says 'It does not support blueprint.'?

**Comment by newbienoobplayer** [comment]
does it mean it will not be able to be copied by blue print or can't be place?

**Comment by hetima** [comment]
It does not support blueprint/copy.  
It will pasted in default short lengths.

**Comment by newbienoobplayer** [comment]
ok, thank you
