### ISSUE TITLE
Sorter gets disconnected when built if the length is too long in DSP 0.9.27.15466

### ISSUE THREAD

**Issue by starfi5h** [hetima/DSP_LongSorter#2]
![image](https://user-images.githubusercontent.com/50672801/213450537-3ef2e256-36c9-43e5-88c9-b96bad297e98.png)

In DSP 0.9.27.15466, they add `PlanetFactory.OnInserterBuilt` which will disconnect the sorter if the sorter length get too long when the sorter is built.

**Comment by hetima** [comment]
fixed in v1.2.2
thanks!
